on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: The version to release.
        required: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: Checkout psanford/tpm-fido
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
        with:
          repository: psanford/tpm-fido
          ref: cd117cecc088cb4fa31f0258a442bbd967dc5b28
          path: tpm-fido
      - name: Merge Repositories
        run: rsync --archive --verbose --exclude .git/ tpm-fido/ .
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568
        with:
          go-version: 1.20.1
      - name: Test
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b
        with:
          version: latest
          args: release --rm-dist --snapshot
      - name: Release
        if: ${{ github.event_name == 'workflow_dispatch' }}
        uses: goreleaser/goreleaser-action@f82d6c1c344bcacabba2c841718984797f664a6b
        with:
          version: ${{ github.event.inputs.version }}
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
